
# Database settings
database:
    connectionString: "server=localhost;user id=bs23;password=bs23;port=1433;database=doctor-appointment-db"

# Server settings

# Maling setting (you have to do a bit of hard work to set up mailing from your own gmail and device)
mail:
    smtpHost: "smtp.gmail.com"
    smtpPort: 587
    senderEmail: "yourgmail"
    password: "generateadevicespecificpasswordfromgmail"
