
# Database settings
database:
    connectionString: "server=localhost;user id=bs23;password=bs23;port=1433;database=doctor-appointment-db"

# Server settings

# Maling setting
mail:
    smtpHost: "smtp.gmail.com"
    smtpPort: 587
    senderEmail: "mdsayeedrahman1999@gmail.com"
    password: "ejuwhtfpmuonegef"
